import path from "node:path";import type{GitWorkspaceAdapter,LocalJob,ProjectPolicy}from"./broker.js";import type{ProcessExecutor}from"./processExecutor.js";
const safeJob=(id:string)=>{if(!/^[A-Za-z0-9_-]{8,80}$/.test(id))throw new Error("invalid_job_id");return id.toLowerCase();};
export class GitCliWorkspaceAdapter implements GitWorkspaceAdapter{
  public constructor(private executor:ProcessExecutor,private git="git",private gh="gh"){}
  public async create({jobId,policy}:{jobId:string;policy:ProjectPolicy}){const remote=(await this.runGit(policy,["remote","get-url",policy.remote])).trim();if(remote!==policy.expectedRemoteUrl)throw new Error("remote_mismatch");await this.runGit(policy,["fetch","--prune",policy.remote]);await this.runGit(policy,["rev-parse","--verify",`${policy.baseRef}^{commit}`]);const id=safeJob(jobId),branch=`jobs/${id}`,cwd=path.join(policy.worktreeRoot,id);await this.runGit(policy,["worktree","add","-b",branch,cwd,policy.baseRef]);return{branch,cwd};}
  public async handoff({job,policy}:{job:LocalJob;policy:ProjectPolicy}){const cwd=path.join(policy.worktreeRoot,safeJob(job.jobId));const branch=(await this.command(this.git,["-C",cwd,"branch","--show-current"])).trim();if(branch!==job.branch)throw new Error("branch_mismatch");if((await this.command(this.git,["-C",cwd,"status","--porcelain"])).trim())throw new Error("uncommitted_changes");const count=Number((await this.command(this.git,["-C",cwd,"rev-list","--count",`${policy.baseRef}..HEAD`])).trim());if(!Number.isInteger(count)||count<1)throw new Error("missing_job_commit");const commitSha=(await this.command(this.git,["-C",cwd,"rev-parse","HEAD"])).trim();if(!/^[a-f0-9]{40}$/.test(commitSha))throw new Error("invalid_commit");await this.command(this.git,["-C",cwd,"push","-u",policy.remote,`${job.branch}:refs/heads/${job.branch}`]);const prUrl=(await this.command(this.gh,["pr","create","--repo",policy.githubRepo,"--head",job.branch,"--base",policy.baseBranch,"--title",`Job ${job.jobId}`,"--body",`Automated handoff for ${job.jobId}. Human review and merge required.`])).trim();if(!/^https:\/\/github\.com\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/pull\/[1-9]\d{0,9}$/.test(prUrl))throw new Error("invalid_pr_url");return{commitSha,prUrl};}
  public async cleanup({job,policy}:{job:LocalJob;policy:ProjectPolicy}){const cwd=path.join(policy.worktreeRoot,safeJob(job.jobId));if(!job.commitSha||!job.prUrl)throw new Error("handoff_evidence_missing");const branch=(await this.command(this.git,["-C",cwd,"branch","--show-current"])).trim();if(branch!==job.branch)throw new Error("branch_mismatch");if((await this.command(this.git,["-C",cwd,"status","--porcelain"])).trim())throw new Error("uncommitted_changes");const head=(await this.command(this.git,["-C",cwd,"rev-parse","HEAD"])).trim();if(head!==job.commitSha)throw new Error("commit_mismatch");const remote=(await this.command(this.git,["-C",cwd,"ls-remote",policy.remote,`refs/heads/${job.branch}`])).trim();if(!remote.startsWith(`${job.commitSha}\t`))throw new Error("remote_evidence_missing");await this.runGit(policy,["worktree","remove",cwd]);await this.runGit(policy,["worktree","prune"]);}
  private runGit(policy:ProjectPolicy,args:string[]){return this.command(this.git,["-C",policy.repoRoot,...args]);}
  private async command(file:string,args:string[]){const out=await this.executor.run(file,args,300_000);if(out.exitCode!==0)throw new Error("git_operation_failed");return out.stdout;}
}
