import assert from "node:assert/strict"; import test from "node:test"; import { GitCliWorkspaceAdapter } from "./gitWorkspaceAdapter.js"; import type { ProcessExecutor, ProcessResult } from "./processExecutor.js"; import type { ProjectPolicy } from "./broker.js";
class Fake implements ProcessExecutor {
  calls:{file:string,args:string[]}[]=[]; existingPr?:string; remoteExists=false; remoteCommit="a".repeat(40); dirty=false; failStart=false; multiplePr=false;
  async run(file:string,args:readonly string[]):Promise<ProcessResult>{
    this.calls.push({file,args:[...args]});if(this.failStart)throw new Error("ENOENT");
    if(file==="git"&&args.includes("push"))this.remoteExists=true;
    const prUrl=this.existingPr??"https://github.com/org/lmns/pull/1";
    const pr={url:prUrl,headRefName:"jobs/job_12345678",headRefOid:"a".repeat(40),baseRefName:"main",state:"OPEN"};
    const text=args.includes("get-url")?"git@github.com:org/lmns.git\n":args.includes("--show-current")?"jobs/job_12345678\n":args.includes("--porcelain")?(this.dirty?" M preserved.txt\n":""):args.includes("--count")?"1\n":args.includes("ls-remote")?(this.remoteExists?`${this.remoteCommit}\trefs/heads/jobs/job_12345678\n`:""):args.includes("rev-parse")?`${"a".repeat(40)}\n`:file==="gh"&&args.includes("list")?JSON.stringify(this.existingPr?(this.multiplePr?[pr,{...pr,url:"https://github.com/org/lmns/pull/10"}]:[pr]):[]):file==="gh"&&args.includes("view")?JSON.stringify(pr):file==="gh"?`${prUrl}\n`:"";
    return {exitCode:0,stdout:text,stderr:""};
  }
}
const policy:ProjectPolicy={project:"lmns",repoRoot:"/repo",worktreeRoot:"/jobs",remote:"origin",expectedRemoteUrl:"git@github.com:org/lmns.git",baseRef:"origin/main",baseBranch:"main",githubRepo:"org/lmns",profiles:["default"]};
test("validates remote and creates from fetched protected base",async()=>{const fake=new Fake();const git=new GitCliWorkspaceAdapter(fake);const result=await git.create({jobId:"job_12345678",policy});assert.equal(result.branch,"jobs/job_12345678");assert.deepEqual(fake.calls[1].args,["-C","/repo","fetch","--prune","origin"]);});
test("pushes branch and creates a human-review PR",async()=>{const fake=new Fake();const git=new GitCliWorkspaceAdapter(fake);const out=await git.handoff({job:{jobId:"job_12345678",project:"lmns",profile:"default",state:"ready",sessionId:"private",branch:"jobs/job_12345678"},policy});assert.equal(out.prUrl,"https://github.com/org/lmns/pull/1");const create=fake.calls.find(call=>call.file==="gh"&&call.args.includes("create"));assert.equal(create?.args.includes("--base"),true);});
test("reuses exact remote and PR evidence without push or PR creation",async()=>{const fake=new Fake();fake.remoteExists=true;fake.existingPr="https://github.com/org/lmns/pull/9";const out=await new GitCliWorkspaceAdapter(fake).handoff({job:{jobId:"job_12345678",project:"lmns",profile:"default",state:"ready",sessionId:"private",branch:"jobs/job_12345678"},policy});assert.equal(out.prUrl,"https://github.com/org/lmns/pull/9");assert.equal(fake.calls.filter(call=>call.file==="git"&&call.args.includes("push")).length,0);assert.equal(fake.calls.filter(call=>call.file==="gh"&&call.args.includes("create")).length,0);});
test("fails closed without force-pushing a conflicting remote",async()=>{const fake=new Fake();fake.remoteExists=true;fake.remoteCommit="b".repeat(40);await assert.rejects(()=>new GitCliWorkspaceAdapter(fake).handoff({job:{jobId:"job_12345678",project:"lmns",profile:"default",state:"ready",sessionId:"private",branch:"jobs/job_12345678"},policy}),/remote_conflict/);assert.equal(fake.calls.some(call=>call.args.includes("push")),false);});
test("fails closed on dirty worktree and ambiguous compatible PRs",async()=>{const dirty=new Fake();dirty.dirty=true;await assert.rejects(()=>new GitCliWorkspaceAdapter(dirty).handoff({job:{jobId:"job_12345678",project:"lmns",profile:"default",state:"ready",sessionId:"private",branch:"jobs/job_12345678"},policy}),/uncommitted_changes/);const ambiguous=new Fake();ambiguous.remoteExists=true;ambiguous.existingPr="https://github.com/org/lmns/pull/9";ambiguous.multiplePr=true;await assert.rejects(()=>new GitCliWorkspaceAdapter(ambiguous).handoff({job:{jobId:"job_12345678",project:"lmns",profile:"default",state:"ready",sessionId:"private",branch:"jobs/job_12345678"},policy}),/pr_ambiguous/);});
test("preserves a bounded process-start code",async()=>{const fake=new Fake();fake.failStart=true;await assert.rejects(()=>new GitCliWorkspaceAdapter(fake).handoff({job:{jobId:"job_12345678",project:"lmns",profile:"default",state:"ready",sessionId:"private",branch:"jobs/job_12345678"},policy}),/git_process_start_failed/);});
test("cleanup verifies durable handoff before removing only the registered worktree",async()=>{const fake=new Fake();fake.remoteExists=true;const git=new GitCliWorkspaceAdapter(fake);await git.cleanup({job:{jobId:"job_12345678",project:"lmns",profile:"default",state:"handoff_ready",sessionId:"private",workspaceId:"w9",branch:"jobs/job_12345678",commitSha:"a".repeat(40),prUrl:"https://github.com/org/lmns/pull/1"},policy});assert.deepEqual(fake.calls.at(-2)?.args,["-C","/repo","worktree","remove","/jobs/job_12345678"]);});
