import assert from "node:assert/strict"; import test from "node:test";
import { HerdrCliAdapter } from "./herdrCliAdapter.js"; import type { ProcessExecutor, ProcessResult } from "./processExecutor.js";
class Fake implements ProcessExecutor { public calls: string[][] = []; public async run(_f: string, args: readonly string[]): Promise<ProcessResult> { this.calls.push([...args]); const cmd = args.slice(0,2).join(" "); if (cmd === "workspace create") return out({result:{workspace:{workspace_id:"w9"}}}); if (cmd === "workspace close") return out({result:{type:"workspace_closed"}}); if (cmd === "api snapshot") return out({result:{snapshot:{panes:[{workspace_id:"w9",pane_id:"w9:p1"}]}}}); if (cmd === "agent start") return out({result:{agent:{agent_status:"idle"}}}); if (cmd === "agent prompt") return out({result:{agent:{agent_status:"working"}}}); if (cmd === "agent get") return out({result:{agent:{agent_status:"done",workspace_id:"w9"}}}); return out({result:{text:"safe output"}}); } }
const out = (body: unknown): ProcessResult => ({exitCode:0,stdout:JSON.stringify(body),stderr:""});
test("creates a readable workspace and agent using argv only", async () => { const fake=new Fake(); const adapter=new HerdrCliAdapter(fake,"codex"); const created=await adapter.create({jobId:"job_12345678",cwd:"/protected/job",profile:"default",label:"add smoke marker"}); assert.equal(created.sessionId,"discord-add-smoke-mark-12345678"); assert.equal(created.workspaceId,"w9"); assert.deepEqual(fake.calls[2].slice(0,8),["agent","start",created.sessionId,"--kind","codex","--pane","w9:p1","--timeout"]); });
test("bounds generated agent names for full public job ids", async () => { const fake=new Fake(); const adapter=new HerdrCliAdapter(fake,"codex"); const created=await adapter.create({jobId:"job_fc2f02db98184f989b2f9109fb4dcc57",cwd:"/protected/job",profile:"default",label:"create a very long descriptive branch name"}); assert.equal(created.sessionId,"discord-create-a-very-fc2f02db"); assert.ok(created.sessionId.length<=32); });
test("maps Herdr agent states and bounds read", async () => { const fake=new Fake(); const adapter=new HerdrCliAdapter(fake,"codex"); assert.equal(await adapter.status("job-job_12345678"),"ready"); assert.equal(await adapter.read("job-job_12345678",25),"safe output"); assert.equal(fake.calls.at(-1)?.at(-3),"25"); });
test("requires the agent to leave a scoped handoff commit", async () => { const fake=new Fake(); const adapter=new HerdrCliAdapter(fake,"codex"); await adapter.prompt("job-12345678","Make the requested file",10_000); const task=fake.calls.at(-1)?.[3] ?? ""; assert.match(task,/leave the requested changes committed/); assert.match(task,/Do not include unrelated changes/); });
test("keeps an approval-blocked agent working instead of allowing handoff",async()=>{const executor:ProcessExecutor={async run(){return out({result:{agent:{agent_status:"blocked"}}})}};assert.equal(await new HerdrCliAdapter(executor,"codex").prompt("discord-task-12345678","task",10_000),"working");});
test("closes only the registered Herdr workspace",async()=>{const fake=new Fake();const adapter=new HerdrCliAdapter(fake,"codex");await adapter.close("discord-task-12345678","w9");assert.deepEqual(fake.calls.at(-1),["workspace","close","w9"]);});
