import assert from "node:assert/strict"; import test from "node:test";
import { HerdrCliAdapter, herdrBinaryForPlatform } from "./herdrCliAdapter.js"; import type { ProcessExecutor, ProcessResult } from "./processExecutor.js";
class Fake implements ProcessExecutor { public calls: string[][] = []; public async run(_f: string, args: readonly string[]): Promise<ProcessResult> { this.calls.push([...args]); const cmd = args.slice(0,2).join(" "); if (cmd === "workspace create") return out({result:{workspace:{workspace_id:"w9"}}}); if (cmd === "workspace close") return out({result:{type:"workspace_closed"}}); if (cmd === "api snapshot") return out({result:{snapshot:{panes:[{workspace_id:"w9",pane_id:"w9:p1"}]}}}); if (cmd === "agent start") return out({result:{agent:{agent_status:"idle"}}}); if (cmd === "agent prompt") return out({result:{agent:{agent_status:"working"}}}); if (cmd === "agent get") return out({result:{agent:{agent_status:"done",workspace_id:"w9"}}}); if (cmd === "agent read") return {exitCode:0,stdout:"safe output",stderr:""}; return out({result:{text:"safe output"}}); } }
const out = (body: unknown): ProcessResult => ({exitCode:0,stdout:JSON.stringify(body),stderr:""});
test("creates a readable workspace and unrestricted Codex agent using argv only", async () => { const fake=new Fake(); const adapter=new HerdrCliAdapter(fake,"codex"); const created=await adapter.create({jobId:"job_12345678",cwd:"/protected/job",profile:"default",label:"add smoke marker"}); assert.equal(created.sessionId,"discord-add-smoke-mark-12345678"); assert.equal(created.workspaceId,"w9"); assert.deepEqual(fake.calls[2],["agent","start",created.sessionId,"--kind","codex","--pane","w9:p1","--timeout","300000","--","--yolo"]); });
test("uses the executable npm shim required by Windows spawn",()=>{assert.equal(herdrBinaryForPlatform("win32"),"herdr.cmd");assert.equal(herdrBinaryForPlatform("darwin"),"herdr");});
test("classifies a missing Herdr executable without exposing the process error",async()=>{const executor:ProcessExecutor={async run(){const error=Object.assign(new Error("sensitive command and path"),{code:"ENOENT"});throw error;}};await assert.rejects(()=>new HerdrCliAdapter(executor,"codex","missing-herdr").create({jobId:"job_12345678",cwd:"/protected/job",profile:"default",label:"task"}),error=>error instanceof Error&&error.message==="herdr_process_start_failed_enoent");});
test("bounds generated agent names for full public job ids", async () => { const fake=new Fake(); const adapter=new HerdrCliAdapter(fake,"codex"); const created=await adapter.create({jobId:"job_fc2f02db98184f989b2f9109fb4dcc57",cwd:"/protected/job",profile:"default",label:"create a very long descriptive branch name"}); assert.equal(created.sessionId,"discord-create-a-very-fc2f02db"); assert.ok(created.sessionId.length<=32); });
test("isolates automated workspaces from interactive shell startup",async()=>{const fake=new Fake();const adapter=new HerdrCliAdapter(fake,"codex","herdr","/protected/runner-shell");await adapter.create({jobId:"job_12345678",cwd:"/protected/job",profile:"default",label:"task"});assert.deepEqual(fake.calls[0],["workspace","create","--cwd","/protected/job","--label","discord-task-12345678","--env","ZDOTDIR=/protected/runner-shell","--no-focus"]);});
test("retries startup until the new workspace shell is ready",async()=>{let starts=0;const fake=new Fake();const original=fake.run.bind(fake);fake.run=async(file,args)=>{if(args[0]==="agent"&&args[1]==="start"&&starts++===0){fake.calls.push([...args]);return{exitCode:1,stdout:JSON.stringify({error:{code:"pane_not_available"}}),stderr:""};}if(args[0]==="agent"&&args[1]==="get"){fake.calls.push([...args]);return{exitCode:1,stdout:JSON.stringify({error:{code:"agent_not_found"}}),stderr:""};}return original(file,args);};const created=await new HerdrCliAdapter(fake,"codex").create({jobId:"job_12345678",cwd:"/protected/job",profile:"default",label:"task"});assert.equal(created.sessionId,"discord-task-12345678");assert.equal(fake.calls.filter(call=>call[0]==="agent"&&call[1]==="start").length,2);});
test("maps Herdr agent states and reads the bounded plain-text transcript", async () => { const fake=new Fake(); const adapter=new HerdrCliAdapter(fake,"codex"); assert.equal(await adapter.status("job-job_12345678"),"ready"); assert.equal(await adapter.read("job-job_12345678",25),"safe output"); assert.deepEqual(fake.calls.at(-1),["agent","read","job-job_12345678","--source","recent-unwrapped","--lines","25"]); });
test("requires the agent to leave a scoped handoff commit", async () => { const fake=new Fake(); const adapter=new HerdrCliAdapter(fake,"codex"); await adapter.prompt("job-12345678","Make the requested file",10_000); const task=fake.calls.at(-1)?.[3] ?? ""; assert.match(task,/leave the requested changes committed/); assert.match(task,/Do not include unrelated changes/); });
test("waits for a settled agent state without accepting transient unknown",async()=>{const fake=new Fake();await new HerdrCliAdapter(fake,"codex").prompt("discord-task-12345678","task",10_000);const call=fake.calls.at(-1)??[];assert.deepEqual(call.slice(0,3),["agent","prompt","discord-task-12345678"]);assert.deepEqual(call.slice(4),["--wait","--timeout","10000"]);assert.equal(call.includes("--until"),false);});
test("keeps an approval-blocked agent working instead of allowing handoff",async()=>{const executor:ProcessExecutor={async run(){return out({result:{agent:{agent_status:"blocked"}}})}};assert.equal(await new HerdrCliAdapter(executor,"codex").prompt("discord-task-12345678","task",10_000),"working");});
test("closes only the registered Herdr workspace",async()=>{const fake=new Fake();const adapter=new HerdrCliAdapter(fake,"codex");await adapter.close("discord-task-12345678","w9");assert.deepEqual(fake.calls.at(-1),["workspace","close","w9"]);});
